export const charDatabase = [
  {
    id: "mario",
    name: "Mario",
    origin: "Super Mario Brothers",
    sigil: "MarioSymbol",
    summary:
      "Mario (マリオ, Mario) is a playable character in Super Smash Bros. Ultimate. He was suggested to appear in the then unnamed Ultimate in its first teaser trailer at the end of the March 8th, 2018 Nintendo Direct, and officially announced in Ultimate's E3 2018 trailer on June 12th, 2018 alongside the rest of the returning roster. Mario is classified as fighter #01.",
  },
  {
    id: "donkeykong",
    name: "Donkey Kong",
    origin: "Donkey Kong",
    sigil: "DKSymbol",
  },
  {
    id: "link",
    name: "Link",
    origin: "The Legend Of Zelda",
    sigil: "ZeldaSymbol",
  },
  {
    id: "samus",
    name: "Samus",
    origin: "Metroid",
    sigil: "MetroidSymbol",
  },
  {
    id: "darksamus",
    name: "Dark Samus",
    origin: "Metroid",
    sigil: "MetroidSymbol",
  },
  {
    id: "yoshi",
    name: "Yoshi",
    origin: "Yoshi's Island",
    sigil: "YoshiSymbol",
  },
  {
    id: "kirby",
    name: "Kirby",
    origin: "Kirby",
    sigil: "KirbySymbol",
  },
  {
    id: "fox",
    name: "Fox",
    origin: "Star Fox",
    sigil: "StarFoxSymbol",
  },
  {
    id: "pikachu",
    name: "Pikachu",
    origin: "Pokemon",
    sigil: "PokemonSymbol",
  },
  {
    id: "luigi",
    name: "Luigi",
    origin: "Super Mario Brothers",
    sigil: "MarioSymbol",
  },
  {
    id: "ness",
    name: "Ness",
    origin: "Earthbound",
    sigil: "EarthboundSymbol",
  },
  {
    id: "captainfalcon",
    name: "Captain Falcon",
    origin: "F-Zero",
    sigil: "FZeroSymbol",
  },
  {
    id: "jigglypuff",
    name: "Jigglypuff",
    origin: "Pokemon",
    sigil: "PokemonSymbol",
  },
  {
    id: "peach",
    name: "Peach",
    origin: "Super Mario Brothers",
    sigil: "MarioSymbol",
  },
  {
    id: "daisy",
    name: "Daisy",
    origin: "Super Mario Brothers",
    sigil: "MarioSymbol",
  },
  {
    id: "bowser",
    name: "Bowser",
    origin: "Super Mario Brothers",
    sigil: "MarioSymbol",
  },
  {
    id: "iceclimbers",
    name: "Ice Climbers",
    origin: "Ice Climber",
    sigil: "IceClimberSymbol",
  },
  {
    id: "sheik",
    name: "Sheik",
    origin: "The Legend Of Zelda",
    sigil: "ZeldaSymbol",
  },
  {
    id: "zelda",
    name: "Zelda",
    origin: "The Legend Of Zelda",
    sigil: "ZeldaSymbol",
  },
  {
    id: "drmario",
    name: "Dr. Mario",
    origin: "Super Mario Brothers",
    sigil: "MarioSymbol",
  },
  {
    id: "pichu",
    name: "Pichu",
    origin: "Pokemon",
    sigil: "PokemonSymbol",
  },
  {
    id: "falco",
    name: "Falco",
    origin: "Star Fox",
    sigil: "StarFoxSymbol",
  },
  {
    id: "marth",
    name: "Marth",
    origin: "Fire Emblem",
    sigil: "FireEmblemSymbol",
  },
  {
    id: "lucina",
    name: "Lucina",
    origin: "Fire Emblem",
    sigil: "FireEmblemSymbol",
  },
  {
    id: "younglink",
    name: "Young Link",
    origin: "The Legend Of Zelda",
    sigil: "ZeldaSymbol",
  },
  {
    id: "ganondorf",
    name: "Ganondorf",
    origin: "The Legend Of Zelda",
    sigil: "ZeldaSymbol",
  },
  {
    id: "mewtwo",
    name: "Mewtwo",
    origin: "Pokemon",
    sigil: "PokemonSymbol",
  },
  {
    id: "roy",
    name: "Roy",
    origin: "Fire Emblem",
    sigil: "FireEmblemSymbol",
  },
  {
    id: "chrom",
    name: "Chrom",
    origin: "Fire Emblem",
    sigil: "FireEmblemSymbol",
  },
  {
    id: "gameandwatch",
    name: "Mr. Game & Watch",
    origin: "Game & Watch",
    sigil: "Game&WatchSymbol",
  },
  {
    id: "metaknight",
    name: "Meta Knight",
    origin: "Kirby",
    sigil: "KirbySymbol",
  },
  {
    id: "pit",
    name: "Pit",
    origin: "Kid Icarus",
    sigil: "KidIcarusSymbol",
  },
  {
    id: "darkpit",
    name: "Dark Pit",
    origin: "Kid Icarus",
    sigil: "KidIcarusSymbol",
  },
  {
    id: "zerosuitsamus",
    name: "Zero Suit Samus",
    origin: "Metroid",
    sigil: "MetroidSymbol",
  },
  {
    id: "wario",
    name: "Wario",
    origin: "Wario",
    sigil: "WarioSymbol",
  },
  {
    id: "snake",
    name: "Snake",
    origin: "Metal Gear",
    sigil: "MetalGearSymbol",
  },
  {
    id: "ike",
    name: "Ike",
    origin: "Fire Emblem",
    sigil: "FireEmblemSymbol",
  },
  {
    id: "pokemontrainer",
    name: "Pokemon Trainer",
    origin: "Pokemon",
    sigil: "PokemonSymbol",
  },
  {
    id: "diddykong",
    name: "Diddy Kong",
    origin: "Donkey Kong",
    sigil: "DKSymbol",
  },
  {
    id: "lucas",
    name: "Lucas",
    origin: "Earthbound",
    sigil: "EarthboundSymbol",
  },
  {
    id: "sonic",
    name: "Sonic",
    origin: "Sonic The Hedgehog",
    sigil: "SonicSymbol",
  },
  {
    id: "dedede",
    name: "King Dedede",
    origin: "Kirby",
    sigil: "KirbySymbol",
  },
  {
    id: "olimar",
    name: "Olimar",
    origin: "Pikmin",
    sigil: "PikminSymbol",
  },
  {
    id: "lucario",
    name: "Lucario",
    origin: "Pokemon",
    sigil: "PokemonSymbol",
  },
  {
    id: "rob",
    name: "R. O. B.",
    origin: "R. O. B.",
    sigil: "ROBSymbol",
  },
  {
    id: "toonlink",
    name: "Toon Link",
    origin: "The Legend Of Zelda",
    sigil: "ZeldaSymbol",
  },
  {
    id: "wolf",
    name: "Wolf",
    origin: "Star Fox",
    sigil: "StarFoxSymbol",
  },
  {
    id: "villager",
    name: "Villager",
    origin: "Animal Crossing",
    sigil: "AnimalCrossingSymbol",
  },
  {
    id: "megaman",
    name: "Mega Man",
    origin: "Mega Man",
    sigil: "MegaManSymbol",
  },
  {
    id: "wiifit",
    name: "Wii Fit Trainer",
    origin: "Wii Fitness",
    sigil: "WiiFitSymbol",
  },
  {
    id: "rosalina",
    name: "Rosalina & Luma",
    origin: "Super Mario Brothers",
    sigil: "MarioSymbol",
  },
  {
    id: "littlemac",
    name: "Little Mac",
    origin: "Punch Out!!!",
    sigil: "PunchOutSymbol",
  },
  {
    id: "greninja",
    name: "Greninja",
    origin: "Pokemon",
    sigil: "PokemonSymbol",
  },
  {
    id: "brawler",
    name: "Mii Brawler",
    origin: "Miiverse",
    sigil: "MiiSymbol",
  },
  {
    id: "gunner",
    name: "Mii Gunner",
    origin: "Miiverse",
    sigil: "MiiSymbol",
  },
  {
    id: "swordfighter",
    name: "Mii Swordfighter",
    origin: "Miiverse",
    sigil: "MiiSymbol",
  },
  {
    id: "palutena",
    name: "Palutena",
    origin: "Kid Icarus",
    sigil: "KidIcarusSymbol",
  },
  {
    id: "pacman",
    name: "Pac-Man",
    origin: "Pac-Man",
    sigil: "PacManSymbol",
  },
  {
    id: "robin",
    name: "Robin",
    origin: "Fire Emblem",
    sigil: "FireEmblemSymbol",
  },
  {
    id: "shulk",
    name: "Shulk",
    origin: "Xenoblade",
    sigil: "XenobladeSymbol",
  },
  {
    id: "bowserjr",
    name: "Bowser Jr.",
    origin: "Super Mario Brothers",
    sigil: "MarioSymbol",
  },
  {
    id: "duckhunt",
    name: "Duck Hunt",
    origin: "Duck Hunt",
    sigil: "DuckHuntSymbol",
  },
  {
    id: "ryu",
    name: "Ryu",
    origin: "Street Fighter",
    sigil: "StreetFighterSymbol",
  },
  {
    id: "ken",
    name: "Ken",
    origin: "Street Fighter",
    sigil: "StreetFighterSymbol",
  },
  {
    id: "cloud",
    name: "Cloud",
    origin: "Final Fantasy",
    sigil: "FinalFantasySymbol",
  },
  {
    id: "corrin",
    name: "Corrin",
    origin: "Fire Emblem",
    sigil: "FireEmblemSymbol",
  },
  {
    id: "bayonetta",
    name: "Bayonetta",
    origin: "Bayonetta",
    sigil: "BayonettaSymbol",
  },
  {
    id: "inkling",
    name: "Inkling",
    origin: "Splatoon",
    sigil: "SplatoonSymbol",
  },
  {
    id: "ridley",
    name: "Ridley",
    origin: "Metroid",
    sigil: "MetroidSymbol",
  },
  {
    id: "simon",
    name: "Simon",
    origin: "Castlevania",
    sigil: "CastlevaniaSymbol",
  },
  {
    id: "richter",
    name: "Richter",
    origin: "Castlevania",
    sigil: "CastlevaniaSymbol",
  },
  {
    id: "kingkrool",
    name: "King K. Rool",
    origin: "Donkey Kong",
    sigil: "DKSymbol",
  },
  {
    id: "isabelle",
    name: "Isabelle",
    origin: "Animal Crossing",
    sigil: "AnimalCrossingSymbol",
  },
  {
    id: "incineroar",
    name: "Incineroar",
    origin: "Pokemon",
    sigil: "PokemonSymbol",
  },
  {
    id: "piranhaplant",
    name: "Piranha Plant",
    origin: "Super Mario Brothers",
    sigil: "MarioSymbol",
  },
  {
    id: "joker",
    name: "Joker",
    origin: "Persona",
    sigil: "PersonaSymbol",
  },
];
