export const dropdownOptions = [
  {
    key: "mario",
    image: { avatar: true, src: "/static/profiles/mario.png" },
    text: "Mario",
    value: "mario",
  },
  {
    key: "donkeykong",
    value: "donkeykong",
    image: { avatar: true, src: "/static/profiles/donkeykong.png" },
    text: "Donkey Kong",
    origin: "Donkey Kong",
    sigil: "DKSymbol",
  },
  {
    key: "link",
    value: "link",
    image: { avatar: true, src: "/static/profiles/link.png" },
    text: "Link",
    origin: "The Legend Of Zelda",
    sigil: "ZeldaSymbol",
  },
  {
    key: "samus",
    value: "samus",
    image: { avatar: true, src: "/static/profiles/samus.png" },
    text: "Samus",
    origin: "Metroid",
    sigil: "MetroidSymbol",
  },
  {
    key: "darksamus",
    value: "darksamus",
    image: { avatar: true, src: "/static/profiles/darksamus.png" },
    text: "Dark Samus",
    origin: "Metroid",
    sigil: "MetroidSymbol",
  },
  {
    key: "yoshi",
    value: "yoshi",
    image: { avatar: true, src: "/static/profiles/yoshi.png" },
    text: "Yoshi",
    origin: "Yoshi's Island",
    sigil: "YoshiSymbol",
  },
  {
    key: "kirby",
    value: "kirby",
    image: { avatar: true, src: "/static/profiles/kirby.png" },
    text: "Kirby",
    origin: "Kirby",
    sigil: "KirbySymbol",
  },
  {
    key: "fox",
    value: "fox",
    image: { avatar: true, src: "/static/profiles/fox.png" },
    text: "Fox",
    origin: "Star Fox",
    sigil: "StarFoxSymbol",
  },
  {
    key: "pikachu",
    value: "pikachu",
    image: { avatar: true, src: "/static/profiles/pikachu.png" },
    text: "Pikachu",
    origin: "Pokemon",
    sigil: "PokemonSymbol",
  },
  {
    key: "luigi",
    value: "luigi",
    image: { avatar: true, src: "/static/profiles/luigi.png" },
    text: "Luigi",
    origin: "Super Mario Brothers",
    sigil: "MarioSymbol",
  },
  {
    key: "ness",
    value: "ness",
    image: { avatar: true, src: "/static/profiles/ness.png" },
    text: "Ness",
    origin: "Earthbound",
    sigil: "EarthboundSymbol",
  },
  {
    key: "captainfalcon",
    value: "captainfalcon",
    image: { avatar: true, src: "/static/profiles/captainfalcon.png" },
    text: "Captain Falcon",
    origin: "F-Zero",
    sigil: "FZeroSymbol",
  },
  {
    key: "jigglypuff",
    value: "jigglypuff",
    image: { avatar: true, src: "/static/profiles/jigglypuff.png" },
    text: "Jigglypuff",
    origin: "Pokemon",
    sigil: "PokemonSymbol",
  },
  {
    key: "peach",
    value: "peach",
    image: { avatar: true, src: "/static/profiles/peach.png" },
    text: "Peach",
    origin: "Super Mario Brothers",
    sigil: "MarioSymbol",
  },
  {
    key: "daisy",
    value: "daisy",
    image: { avatar: true, src: "/static/profiles/daisy.png" },
    text: "Daisy",
    origin: "Super Mario Brothers",
    sigil: "MarioSymbol",
  },
  {
    key: "bowser",
    value: "bowser",
    image: { avatar: true, src: "/static/profiles/bowser.png" },
    text: "Bowser",
    origin: "Super Mario Brothers",
    sigil: "MarioSymbol",
  },
  {
    key: "iceclimbers",
    value: "iceclimbers",
    image: { avatar: true, src: "/static/profiles/iceclimbers.png" },
    text: "Ice Climbers",
    origin: "Ice Climber",
    sigil: "IceClimberSymbol",
  },
  {
    key: "sheik",
    value: "sheik",
    image: { avatar: true, src: "/static/profiles/sheik.png" },
    text: "Sheik",
    origin: "The Legend Of Zelda",
    sigil: "ZeldaSymbol",
  },
  {
    key: "zelda",
    value: "zelda",
    image: { avatar: true, src: "/static/profiles/zelda.png" },
    text: "Zelda",
    origin: "The Legend Of Zelda",
    sigil: "ZeldaSymbol",
  },
  {
    key: "drmario",
    value: "drmario",
    image: { avatar: true, src: "/static/profiles/drmario.png" },
    text: "Dr. Mario",
    origin: "Super Mario Brothers",
    sigil: "MarioSymbol",
  },
  {
    key: "pichu",
    value: "pichu",
    image: { avatar: true, src: "/static/profiles/pichu.png" },
    text: "Pichu",
    origin: "Pokemon",
    sigil: "PokemonSymbol",
  },
  {
    key: "falco",
    value: "falco",
    image: { avatar: true, src: "/static/profiles/falco.png" },
    text: "Falco",
    origin: "Star Fox",
    sigil: "StarFoxSymbol",
  },
  {
    key: "marth",
    value: "marth",
    image: { avatar: true, src: "/static/profiles/marth.png" },
    text: "Marth",
    origin: "Fire Emblem",
    sigil: "FireEmblemSymbol",
  },
  {
    key: "lucina",
    value: "lucina",
    image: { avatar: true, src: "/static/profiles/lucina.png" },
    text: "Lucina",
    origin: "Fire Emblem",
    sigil: "FireEmblemSymbol",
  },
  {
    key: "younglink",
    value: "younglink",
    image: { avatar: true, src: "/static/profiles/younglink.png" },
    text: "Young Link",
    origin: "The Legend Of Zelda",
    sigil: "ZeldaSymbol",
  },
  {
    key: "ganondorf",
    value: "ganondorf",
    image: { avatar: true, src: "/static/profiles/ganondorf.png" },
    text: "Ganondorf",
    origin: "The Legend Of Zelda",
    sigil: "ZeldaSymbol",
  },
  {
    key: "mewtwo",
    value: "mewtwo",
    image: { avatar: true, src: "/static/profiles/mewtwo.png" },
    text: "Mewtwo",
    origin: "Pokemon",
    sigil: "PokemonSymbol",
  },
  {
    key: "roy",
    value: "roy",
    image: { avatar: true, src: "/static/profiles/roy.png" },
    text: "Roy",
    origin: "Fire Emblem",
    sigil: "FireEmblemSymbol",
  },
  {
    key: "chrom",
    value: "chrom",
    image: { avatar: true, src: "/static/profiles/chrom.png" },
    text: "Chrom",
    origin: "Fire Emblem",
    sigil: "FireEmblemSymbol",
  },
  {
    key: "gameandwatch",
    value: "gameandwatch",
    image: { avatar: true, src: "/static/profiles/gameandwatch.png" },
    text: "Mr. Game & Watch",
    origin: "Game & Watch",
    sigil: "Game&WatchSymbol",
  },
  {
    key: "metaknight",
    value: "metaknight",
    image: { avatar: true, src: "/static/profiles/metaknight.png" },
    text: "Meta Knight",
    origin: "Kirby",
    sigil: "KirbySymbol",
  },
  {
    key: "pit",
    value: "pit",
    image: { avatar: true, src: "/static/profiles/pit.png" },
    text: "Pit",
    origin: "Kid Icarus",
    sigil: "KidIcarusSymbol",
  },
  {
    key: "darkpit",
    value: "darkpit",
    image: { avatar: true, src: "/static/profiles/darkpit.png" },
    text: "Dark Pit",
    origin: "Kid Icarus",
    sigil: "KidIcarusSymbol",
  },
  {
    key: "zerosuitsamus",
    value: "zerosuitsamus",
    image: { avatar: true, src: "/static/profiles/zerosuitsamus.png" },
    text: "Zero Suit Samus",
    origin: "Metroid",
    sigil: "MetroidSymbol",
  },
  {
    key: "wario",
    value: "wario",
    image: { avatar: true, src: "/static/profiles/wario.png" },
    text: "Wario",
    origin: "Wario",
    sigil: "WarioSymbol",
  },
  {
    key: "snake",
    value: "snake",
    image: { avatar: true, src: "/static/profiles/snake.png" },
    text: "Snake",
    origin: "Metal Gear",
    sigil: "MetalGearSymbol",
  },
  {
    key: "ike",
    value: "ike",
    image: { avatar: true, src: "/static/profiles/ike.png" },
    text: "Ike",
    origin: "Fire Emblem",
    sigil: "FireEmblemSymbol",
  },
  {
    key: "pokemontrainer",
    value: "pokemontrainer",
    image: { avatar: true, src: "/static/profiles/pokemontrainer.png" },
    text: "Pokemon Trainer",
    origin: "Pokemon",
    sigil: "PokemonSymbol",
  },
  {
    key: "diddykong",
    value: "diddykong",
    image: { avatar: true, src: "/static/profiles/diddykong.png" },
    text: "Diddy Kong",
    origin: "Donkey Kong",
    sigil: "DKSymbol",
  },
  {
    key: "lucas",
    value: "lucas",
    image: { avatar: true, src: "/static/profiles/lucas.png" },
    text: "Lucas",
    origin: "Earthbound",
    sigil: "EarthboundSymbol",
  },
  {
    key: "sonic",
    value: "sonic",
    image: { avatar: true, src: "/static/profiles/sonic.png" },
    text: "Sonic",
    origin: "Sonic The Hedgehog",
    sigil: "SonicSymbol",
  },
  {
    key: "dedede",
    value: "dedede",
    image: { avatar: true, src: "/static/profiles/dedede.png" },
    text: "King Dedede",
    origin: "Kirby",
    sigil: "KirbySymbol",
  },
  {
    key: "olimar",
    value: "olimar",
    image: { avatar: true, src: "/static/profiles/olimar.png" },
    text: "Olimar",
    origin: "Pikmin",
    sigil: "PikminSymbol",
  },
  {
    key: "lucario",
    value: "lucario",
    image: { avatar: true, src: "/static/profiles/lucario.png" },
    text: "Lucario",
    origin: "Pokemon",
    sigil: "PokemonSymbol",
  },
  {
    key: "rob",
    value: "rob",
    image: { avatar: true, src: "/static/profiles/rob.png" },
    text: "R. O. B.",
    origin: "R. O. B.",
    sigil: "ROBSymbol",
  },
  {
    key: "toonlink",
    value: "toonlink",
    image: { avatar: true, src: "/static/profiles/toonlink.png" },
    text: "Toon Link",
    origin: "The Legend Of Zelda",
    sigil: "ZeldaSymbol",
  },
  {
    key: "wolf",
    value: "wolf",
    image: { avatar: true, src: "/static/profiles/wolf.png" },
    text: "Wolf",
    origin: "Star Fox",
    sigil: "StarFoxSymbol",
  },
  {
    key: "villager",
    value: "villager",
    image: { avatar: true, src: "/static/profiles/villager.png" },
    text: "Villager",
    origin: "Animal Crossing",
    sigil: "AnimalCrossingSymbol",
  },
  {
    key: "megaman",
    value: "megaman",
    image: { avatar: true, src: "/static/profiles/megaman.png" },
    text: "Mega Man",
    origin: "Mega Man",
    sigil: "MegaManSymbol",
  },
  {
    key: "wiifit",
    value: "wiifit",
    image: { avatar: true, src: "/static/profiles/wiifit.png" },
    text: "Wii Fit Trainer",
    origin: "Wii Fitness",
    sigil: "WiiFitSymbol",
  },
  {
    key: "rosalina",
    value: "rosalina",
    image: { avatar: true, src: "/static/profiles/rosalina.png" },
    text: "Rosalina & Luma",
    origin: "Super Mario Brothers",
    sigil: "MarioSymbol",
  },
  {
    key: "littlemac",
    value: "littlemac",
    image: { avatar: true, src: "/static/profiles/littlemac.png" },
    text: "Little Mac",
    origin: "Punch Out!!!",
    sigil: "PunchOutSymbol",
  },
  {
    key: "greninja",
    value: "greninja",
    image: { avatar: true, src: "/static/profiles/greninja.png" },
    text: "Greninja",
    origin: "Pokemon",
    sigil: "PokemonSymbol",
  },
  {
    key: "brawler",
    value: "brawler",
    image: { avatar: true, src: "/static/profiles/brawler.png" },
    text: "Mii Brawler",
    origin: "Miiverse",
    sigil: "MiiSymbol",
  },
  {
    key: "gunner",
    value: "gunner",
    image: { avatar: true, src: "/static/profiles/gunner.png" },
    text: "Mii Gunner",
    origin: "Miiverse",
    sigil: "MiiSymbol",
  },
  {
    key: "swordfighter",
    value: "swordfighter",
    image: { avatar: true, src: "/static/profiles/swordfighter.png" },
    text: "Mii Swordfighter",
    origin: "Miiverse",
    sigil: "MiiSymbol",
  },
  {
    key: "palutena",
    value: "palutena",
    image: { avatar: true, src: "/static/profiles/palutena.png" },
    text: "Palutena",
    origin: "Kid Icarus",
    sigil: "KidIcarusSymbol",
  },
  {
    key: "pacman",
    value: "pacman",
    image: { avatar: true, src: "/static/profiles/pacman.png" },
    text: "Pac-Man",
    origin: "Pac-Man",
    sigil: "PacManSymbol",
  },
  {
    key: "robin",
    value: "robin",
    image: { avatar: true, src: "/static/profiles/robin.png" },
    text: "Robin",
    origin: "Fire Emblem",
    sigil: "FireEmblemSymbol",
  },
  {
    key: "shulk",
    value: "shulk",
    image: { avatar: true, src: "/static/profiles/shulk.png" },
    text: "Shulk",
    origin: "Xenoblade",
    sigil: "XenobladeSymbol",
  },
  {
    key: "bowserjr",
    value: "bowserjr",
    image: { avatar: true, src: "/static/profiles/bowserjr.png" },
    text: "Bowser Jr.",
    origin: "Super Mario Brothers",
    sigil: "MarioSymbol",
  },
  {
    key: "duckhunt",
    value: "duckhunt",
    image: { avatar: true, src: "/static/profiles/duckhunt.png" },
    text: "Duck Hunt",
    origin: "Duck Hunt",
    sigil: "DuckHuntSymbol",
  },
  {
    key: "ryu",
    value: "ryu",
    image: { avatar: true, src: "/static/profiles/ryu.png" },
    text: "Ryu",
    origin: "Street Fighter",
    sigil: "StreetFighterSymbol",
  },
  {
    key: "ken",
    value: "ken",
    image: { avatar: true, src: "/static/profiles/ken.png" },
    text: "Ken",
    origin: "Street Fighter",
    sigil: "StreetFighterSymbol",
  },
  {
    key: "cloud",
    value: "cloud",
    image: { avatar: true, src: "/static/profiles/cloud.png" },
    text: "Cloud",
    origin: "Final Fantasy",
    sigil: "FinalFantasySymbol",
  },
  {
    key: "corrin",
    value: "corrin",
    image: { avatar: true, src: "/static/profiles/corrin.png" },
    text: "Corrin",
    origin: "Fire Emblem",
    sigil: "FireEmblemSymbol",
  },
  {
    key: "bayonetta",
    value: "bayonetta",
    image: { avatar: true, src: "/static/profiles/bayonetta.png" },
    text: "Bayonetta",
    origin: "Bayonetta",
    sigil: "BayonettaSymbol",
  },
  {
    key: "inkling",
    value: "inkling",
    image: { avatar: true, src: "/static/profiles/inkling.png" },
    text: "Inkling",
    origin: "Splatoon",
    sigil: "SplatoonSymbol",
  },
  {
    key: "ridley",
    value: "ridley",
    image: { avatar: true, src: "/static/profiles/ridley.png" },
    text: "Ridley",
    origin: "Metroid",
    sigil: "MetroidSymbol",
  },
  {
    key: "simon",
    value: "simon",
    image: { avatar: true, src: "/static/profiles/simon.png" },
    text: "Simon",
    origin: "Castlevania",
    sigil: "CastlevaniaSymbol",
  },
  {
    key: "richter",
    value: "richter",
    image: { avatar: true, src: "/static/profiles/richter.png" },
    text: "Richter",
    origin: "Castlevania",
    sigil: "CastlevaniaSymbol",
  },
  {
    key: "kingkrool",
    value: "kingkrool",
    image: { avatar: true, src: "/static/profiles/kingkrool.png" },
    text: "King K. Rool",
    origin: "Donkey Kong",
    sigil: "DKSymbol",
  },
  {
    key: "isabelle",
    value: "isabelle",
    image: { avatar: true, src: "/static/profiles/isabelle.png" },
    text: "Isabelle",
    origin: "Animal Crossing",
    sigil: "AnimalCrossingSymbol",
  },
  {
    key: "incineroar",
    value: "incineroar",
    image: { avatar: true, src: "/static/profiles/incineroar.png" },
    text: "Incineroar",
    origin: "Pokemon",
    sigil: "PokemonSymbol",
  },
  {
    key: "piranhaplant",
    value: "piranhaplant",
    image: { avatar: true, src: "/static/profiles/piranhaplant.png" },
    text: "Piranha Plant",
    origin: "Super Mario Brothers",
    sigil: "MarioSymbol",
  },
  {
    key: "joker",
    value: "joker",
    image: { avatar: true, src: "/static/profiles/joker.png" },
    text: "Joker",
    origin: "Persona",
    sigil: "PersonaSymbol",
  },
];
